name: viajes_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-257.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets: 
    - assets/img/profile.jpg
    - assets/img/m1.jpg
    - assets/img/m2.jpg
    - assets/img/m3.jpg
    - assets/img/profile5.jpg
    - assets/img/profile6.jpg
    - assets/img/profile7.jpg